name: sse-demo

services:
  ui:
    image: node:24.3-bookworm
    environment:
      - NODE_ENV=development
    working_dir: /react/src
    volumes:
      - ./ui:/react/src
    command: sh -c 'npm install && npm run dev'
    ports:
      - "3000:3000"
    networks:
      - net

  api:
    image: golang:1.23-alpine
    working_dir: /go/src
    command: go run main.go
    volumes:
      - ./api:/go/src
    ports:
      - 8080:8080
    networks:
      - net

networks:
  net:
    driver: bridge
