services:
  ui:
    image: node:22.11.0-bullseye
    container_name: ui
    environment:
      - NODE_ENV=development
    working_dir: /react/src
    volumes:
      - ./ui:/react/src
    command: sh -c 'npm install && npm run dev'
    ports:
      - "3000:3000"
    networks:
      - app-network

  api:
    image: golang:1.23-alpine
    container_name: api
    working_dir: /go/src
    command: go run main.go
    volumes:
      - ./api:/go/src
    ports:
      - 8080:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
